version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  app:
    image: codemonkey076/php7.4-alpine:1.0
    container_name: app
    hostname: app
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./profile:/home/shane
    ports:
      - 9000:9000
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - 8025:8025
    networks:
      - laravel

  horizon:
    image: codemonkey076/php7.4-alpine:1.0
    restart: always
    depends_on: 
      - app
    volumes:
      - ./src:/var/www
    command: php /var/www/artisan horizon
    networks:
      - laravel

  watcher:
    image: codemonkey076/php7.4-alpine:1.0
    depends_on: 
      - app
    restart: always
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    command: npm run watch
    networks:
      - laravel

  websockets:
    image: codemonkey076/php7.4-alpine:1.0
    depends_on: 
      - app
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    command: php /var/www/artisan websockets:serve
    networks:
      - laravel
